In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import SGDClassifier  #this is linear SVM in sklearn
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression
from sklearn import metrics

In [2]:
data = pd.read_csv('train_test.csv')

In [3]:
x_train, x_test, y_train, y_test = train_test_split(data.iloc[:,:25], data.iloc[:,25], 
                                                    test_size = 0.2,
                                                    random_state = 0)  #random_state is the random seed. change if needed

In [21]:
model = LogisticRegression(class_weight ={1:0.82,0:0.18})
model_2 = SGDClassifier(loss='log')

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:84: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


In [22]:
model_2.fit(x_train, y_train)

SGDClassifier(alpha=0.0001, average=False, class_weight=None, epsilon=0.1,
       eta0=0.0, fit_intercept=True, l1_ratio=0.15,
       learning_rate='optimal', loss='log', max_iter=5, n_iter=None,
       n_jobs=1, penalty='l2', power_t=0.5, random_state=None,
       shuffle=True, tol=None, verbose=0, warm_start=False)

In [6]:
model.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight={1: 0.82, 0: 0.18}, dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)

In [7]:
predicted = model.predict_proba(x_test)

In [8]:
model.classes_

array([0, 1])

In [9]:
predicted

array([[0.49658857, 0.50341143],
       [0.49658857, 0.50341143],
       [0.4874673 , 0.5125327 ],
       ...,
       [0.49523715, 0.50476285],
       [0.49523715, 0.50476285],
       [0.49523715, 0.50476285]])

In [10]:
class_1_prob = []
for p in predicted:
    class_1_prob.append(p[1])

In [12]:
class_1_prob

[0.5034101112125465,
 0.5034101112125465,
 0.5125324896866549,
 0.5138837529121812,
 0.5034101112125465,
 0.5034101112125465,
 0.5138837529121812,
 0.5034101112125465,
 0.5047622277237157,
 0.5034101112125465,
 0.5034101112125465,
 0.5034101112125465,
 0.7071847018378151,
 0.5034101112125465,
 0.29577113304481223,
 0.6739157513584385,
 0.5125324896866549,
 0.5125324896866549,
 0.5034101112125465,
 0.5125324896866549,
 0.5125324896866549,
 0.5138837529121812,
 0.5034101112125465,
 0.5138837529121812,
 0.5138837529121812,
 0.5034101112125465,
 0.5034101112125465,
 0.5047622277237157,
 0.5047622277237157,
 0.5034101112125465,
 0.5034101112125465,
 0.5034101112125465,
 0.5034101112125465,
 0.5034101112125465,
 0.5034101112125465,
 0.5216465271406007,
 0.5034101112125465,
 0.5125324896866549,
 0.5034101112125465,
 0.5034101112125465,
 0.5061142745809902,
 0.5034101112125465,
 0.5216465271406007,
 0.5034101112125465,
 0.5216465271406007,
 0.5034101112125465,
 0.5034101112125465,
 0.503410111

In [13]:
rank = np.argsort(-np.array(class_1_prob))

In [14]:
rank

array([15371,  7709,  2145, ..., 12386,  7688,  5136])

In [15]:
len(rank)

15570

In [16]:
np.mean(np.array(y_test)[rank][:1557])

0.37122671804752727

In [11]:
out_of_date = pd.read_csv('out_of_date.csv')

In [23]:
predicted_out = model_2.predict_proba(out_of_date.iloc[:,:25])

In [24]:
class_1_prob_out = []
for p in predicted_out:
    class_1_prob_out.append(p[1])

In [25]:
rank_out = np.argsort(-np.array(class_1_prob_out))

In [26]:
sum(np.array(out_of_date.iloc[:,25]))

4338

In [27]:
sum(np.array(out_of_date.iloc[:,25])[rank_out][:1701])

659

In [28]:
len(out_of_date)

17016

In [29]:
sum(np.array(out_of_date.iloc[:,25])[rank_out][:1701])/sum(np.array(out_of_date.iloc[:,25]))

0.15191332411249422

In [45]:
sum(out_of_date.iloc[:,25].sample(1701))/sum(np.array(out_of_date.iloc[:,25]))

0.09981558321807285

In [26]:
1-np.mean(np.array(out_of_date.iloc[:,25])[rank_out][:1701])

0.6090534979423868